# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"datasourceNodes": "00_core.ipynb",
         "modelNodes": "00_core.ipynb",
         "stakeholderNodes": "00_core.ipynb",
         "nodesDict": "00_core.ipynb",
         "G": "00_core.ipynb",
         "pos": "00_core.ipynb",
         "color": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://saurk.github.io/dependencygraph/"

git_url = "https://github.com/saurk/dependencygraph/tree/master/"

def custom_doc_links(name): return None
